data:
  f0_extractor: 'parselmouth' # 'parselmouth', 'dio', 'harvest', or 'crepe'
  us_uv: false
  f0_min: 65 # about C2
  f0_max: 800 # about G5
  duration: 0.3483 # Audio duration during training, must be less than the duration of the shortest audio clip
  train_path: op16/train # Create a folder named "audio" under this path and put the audio clip in it
  valid_path: op16/val # Create a folder named "audio" under this path and put the audio clip in it
  extensions: # List of extension included in the data collection
    - wav
mel:
  sampling_rate: 16000
  num_mels: 128
  n_fft: 1024
  win_size: 1024
  hop_size: 160
  fmin: 0
  fmax: 8000
model:
  type: 'TransformerF0BCE'
  input_channel: 128 # same as mel.num_mels
  out_dims: 360
  n_layers: 3
  n_chans: 512
  use_siren: false
  use_full: false
  confidence: false
  f0_min: 32.70
  f0_max: 1975.5
  n_spk: 199 # max number of speakers
loss:
  loss_mse_scale: 10
  loss_l2_regularization: true
  loss_l2_regularization_scale: 1
  loss_grad1_mse: false
  loss_grad1_mse_scale: 1
device: cuda
env:
  expdir: exp/f0bce_test_b_1
  gpu_id: 0
train:
  aug_keyshift: true
  keyshift_min: -12
  keyshift_max: 12
  aug_noise: false
  noise_ratio: 0.7
  aug_flip: false
  aug_mask: false
  aug_mask_v_o: false
  aug_mask_vertical_factor: 0.05
  aug_mask_vertical_factor_v_o: 0.3
  aug_mask_iszeropad_mode: 'randon' # randon zero or noise
  aug_mask_block_num: 1
  aug_mask_block_num_v_o: 4
  num_workers: 8 # If your cpu and gpu are both very strong, set to 0 may be faster!
  amp_dtype: fp32 # only can ues fp32, else nan
  batch_size: 128
  cache_all_data: true # Save Internal-Memory or Graphics-Memory if it is false, but may be slow
  cache_device: 'cpu' # Set to 'cuda' to cache the data into the Graphics-Memory, fastest speed for strong gpu
  epochs: 100000
  interval_log: 100
  interval_val: 5000
  interval_force_save: 5000
  lr: 0.0005
  decay_step: 200000
  gamma: 0.5
  weight_decay: 0
  save_opt: false
