data:
  f0_extractor: 'crepe' # 'parselmouth', 'dio', 'harvest', or 'crepe'
  us_uv: true
  f0_min: 65 # about C2
  f0_max: 800 # about G5
  win_size: 1024
  hop_size: 512
  duration: 0.3483 # Audio duration during training, must be less than the duration of the shortest audio clip
  train_path: data/train # Create a folder named "audio" under this path and put the audio clip in it
  valid_path: data/val # Create a folder named "audio" under this path and put the audio clip in it
  extensions: # List of extension included in the data collection
    - wav
model:
  type: 'TransformerF0BCE'
  input_channel: 128 # same as mel.num_mels
  out_dims: 360
  n_layers: 12
  n_chans: 512
  use_siren: false
  use_full: false
  confidence: false
  f0_min: 32.70
  f0_max: 1975.5
  n_spk: 2 # max number of speakers
loss:
  loss_mse_scale: 10
  loss_l2_regularization: false
  loss_l2_regularization_scale: 1
  loss_grad1_mse: false
  loss_grad1_mse_scale: 1
device: cuda
env:
  expdir: exp/f0bce_test
  gpu_id: 0
train:
  num_workers: 8 # If your cpu and gpu are both very strong, set to 0 may be faster!
  amp_dtype: fp32 # only can ues fp32, else nan
  batch_size: 128
  cache_all_data: true # Save Internal-Memory or Graphics-Memory if it is false, but may be slow
  cache_device: 'cuda' # Set to 'cuda' to cache the data into the Graphics-Memory, fastest speed for strong gpu
  epochs: 100000
  interval_log: 100
  interval_val: 5000
  interval_force_save: 5000
  lr: 0.0005
  decay_step: 100000
  gamma: 0.5
  weight_decay: 0
  save_opt: false
